services:
  # Aplicaci√≥n NestJS
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-help-desk-app
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      PORT: 3004
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    networks:
      - tech-help-desk-network

networks:
  tech-help-desk-network:
    driver: bridge
